version: '3.8'
services:
    server:
        build: ./server/
        command: users.py
        ports: 
            - 8080:8080
    client:
        build: ./tests/
        entrypoint: sh -c "pytest -v -s test_example.py --disable-warnings"
        #command: -c "pytest -v -s -n2 --fixtures=conftest.py test_example.py --disable-warnings; tail -f ../dev/null"
        network_mode: host
        depends_on: 
            - server
